### ISSUE TITLE
> Hello, in this project, using pre-trained weights works fine for climbing stairs, but when descending stairs, the model tends to step on the edge at the second-to-last step, leading to a fall. How can this issue be resolved? Thank you for your reply.

### ISSUE THREAD

**Issue by Wangzeyu6** [rohanpsingh/LearningHumanoidWalking#31]

**Comment by rohanpsingh** [comment]
Hi, 
I pushed 7f28e0327293f9fbc87587c21d00b24c9ff7efbc which should fix this issue. Please let me know if you still face it.

I think it occurs because during training, the robot never really reaches the end of the stairs as the max episode length is too small. Of course, a more reasonable solution would be to randomize the `num_steps` parameter during training. This would expose the agent to stairs of varying number of steps in the stair sequence. For now, I created a much simpler fix which doesn't require retraining.
